### ISSUE TITLE
[FIXED] Интеграция в Антизапрет

### ISSUE THREAD

**Issue by sergeevabc** [ivan386/js-ip-filter#1]
Иван, доброго дня.

Из [комментариев][1] на Хабре следует, что вы умудрились оптимизировать скрипт Антизапрета. Я уже немного меняю его перед использованием, чтобы открывать «луковые» адреса (см. ниже), и теперь надеюсь узнать, какие строчки в нём надо удалить/заменить на ваши. 
```
@echo off
wget -q https://antizapret.prostovpn.org/proxy.pac -O antizapret.pac
sed -i "/FindProxyForURL/ s:$:\n  if (host.endsWith(\".onion\")) {return \"SOCKS5 127.0.0.1\:9050\";}:" antizapret.pac
```

### Решение: [antizapret386.cmd][2]

[1]: https://habr.com/post/430428/#comment_19394186
[2]: https://gist.github.com/sergeevabc/8a51ac9de9d40eb3160ee9944103a894

**Comment by ivan386** [comment]
Конкретно эти скрипты оптимизируют IP фильтр делая его компактнее. Тут просто заменой не обойтись. Необходимо преобразовать список IP в дельта фильтр при помощи функции make_ip_filter. 

## Что здесь
Здесь находятся два скрипта:
1. [make-ip-filter.js](https://github.com/ivan386/js-ip-filter/blob/master/make-ip-filter.js)
    Этот скрипт отвечает за сжатие списка IP вида ```['203.0.113.53', '203.0.113.114', '198.51.100.23', ...]``` в строку(дельта фильтр) вида ```"-zij2io 2jhsi 8g 9u3m 4xewq 7e 2m 3u 2i 4s ..."```
2. [ip-filter.js](https://github.com/ivan386/js-ip-filter/blob/master/ip-filter.js)
    Это уже непосредственно функции IP фильтра с примером использования.

Скрипты писались с расчётом на сжатие списка IP который предоставляет [API rublacklist](https://reestr.rublacklist.net/article/api). Функция make_ip_filter выбрасывает из списка IPv4 диапазоны (Пример диапазона: '203.0.113.53/24') и IPv6 так что их надо обрабатывать отдельно.

## Как интегрировать в Антизапрет
В PAC файле Антизапрета IP фильтр представлен строками:

1. Данные фильтра
    ```javascript
    d_ipaddr = "\
    01b3c...
    ...
    ...5a24\
    ".match(/.{8}/g);
    ```

1. И код
    ```javascript
    if (iphex) {
     for (var i = 0; i < d_ipaddr.length; i++)
      if (iphex === d_ipaddr[i]) {yip = 1; break;}
    }
    ```

Для того чтобы заменить его необходимо:
1. Преобразовать список IP (d_ipaddr) в дельта фильтр (ip_filter). 
    1. Для этого необходимо вернуть список IP в исходный вид ```['203.0.113.53', '203.0.113.114', '198.51.100.23', ...]``` функцией:
        ````javascript
        d_ipaddr = d_ipaddr.map(ip=>{
           ip = parseInt(ip, 16)
           return [(ip >>> 8*3) & 255, (ip >>> 8*2) & 255, (ip >>> 8) & 255, ip & 255].join(".")
        })
        ````
    2. Далее преобразовать его в дельта фильтр функцией make_ip_filter из [make-ip-filter.js](https://github.com/ivan386/js-ip-filter/blob/master/make-ip-filter.js)
        ````javascript
        ip_filter  = make_ip_filter( d_ipaddr )
        ````
        В результате должна получиться строка вида: ````-g1c9hc 3 2 4 1 2 3 8 2 0 1 6 1 0 a 5 1-2...````

2. Заменяем код в PAC файле.
    1. Заменяем первую часть
        ```javascript
        d_ipaddr = "\
        01b3c...
        ...
        ...5a24\
        ".match(/.{8}/g);
         ```
         На код из [ip-filter.js](https://github.com/ivan386/js-ip-filter/blob/master/ip-filter.js) заменяя пример на результат полученный на предыдущем этапе.
         ```javascript
		var ip_filter = "-g1c9hc 3 2 4 1 2 3 8 2 0 1 6 1 0 a 5 1-2 2 1-1 ..."; // <--  Здесь подставили результат преобразования

		ip_filter = ip_filter.replace(/([0-9a-z])-/g, '$1 -').split(' ');

		var ip_number = 0;
		var repeat = 0;
		var ip_dict = {};

		for (var index = 0; index < ip_filter.length; index++)
		{
			var value = parseInt(ip_filter[index], 36);
			
			if (index == 0 || value > 0)
			{
				ip_number += (repeat = value);
				ip_dict[ip_number] = true;
			}
				
			else
			{
				for ( var counter = value
					; counter < 1
					; counter++ )
				{
					ip_number += repeat;
					ip_dict[ip_number] = true;
				}
			}
		}

		ip_filter = ip_dict

		function ip_to_number(ip_string)
		{
			for (var index = 0, ip_number = 0
				, octets = ip_string.split('.')
				; index < ip_string.length
				; index++ )
				ip_number |= octets[index] << (8*(3-index));
			
			return ip_number;
		}

		function check_ip(ip)
		{
			return ip_filter[ip_to_number(ip)]
		}
          ````
    2. Заменяем вторую часть
         ```javascript
         if (iphex) {
          for (var i = 0; i < d_ipaddr.length; i++)
           if (iphex === d_ipaddr[i]) {yip = 1; break;}
         }
        ```
        на
        ```javascript
        if(oip && check_ip(oip)){yip = 1}
        ```
Код интеграции написан без проверки так что тестируйте и исправляйте если что.

**Comment by ivan386** [comment]
На данный момент из HEX списка IP адресов Антизапрета размером 500KB генерируется дельта фильтр размером 87KB.

**Comment by sergeevabc** [comment]
Гм, в батник это не запихнёшь из-за преобразования чёрнокнижных айпишников в дельту на JS, а значит массовый пользователь пока потерян. Пробовал компилятор из Microsoft.NET, но не вышло: 
```console
$ C:\Windows\Microsoft.NET\Framework64\v4.0.30319 $ jsc make-ip-filter.js
Microsoft (R) JScript Compiler version 14.00.2558
for Microsoft (R) .NET Framework version 4.0.30319
Copyright (C) Microsoft Corporation. All rights reserved.

error JS1195: Expected expression
error JS1197: Too many errors. The file might not be a JScript file
```
Ведь пока @ValdikSS решает, встраивать ли эту оптимизацию в Антизапрет, массовый пользователь мог бы качать [чёрнокнижный JSON][1] с помощью ```aria2/curl/wget``` и затем конвертировать его в дельту как-то так ```blackdelta.exe blackips.json```, а вывод с помощью ```awk/sed``` вставлять в PAC.

Выполнил это руками, взяв результат работы ```make-ip-filter``` с помощью инструкции ```console.log``` и вставив его с остальными инструкциями из второго шага в PAC — получился [antizapret-ivan.pac][2], который, увы, отказался работать. Рутрекер не открылся, а заход на чернокнижные айпишники (например, ```104.16.39.41 и 94.23.148.60```) привёл к ошибке соединения: ```The page isn’t redirecting properly```.

[1]: https://reestr.rublacklist.net/api/v2/ips/json
[2]: https://linx.li/s/8dbtx6pp.pac

**Comment by ivan386** [comment]
Переписал [генератор для CScript (make-ip-filter.cscript.js)](https://github.com/ivan386/js-ip-filter/blob/master/make-ip-filter.cscript.js).
Добавил [пример его использования(compile_proxy_pac.cmd)](https://github.com/ivan386/js-ip-filter/blob/master/compile_proxy_pac.cmd)
На вход принимает CSV список IP.

Прокси Антизапрета пропускает через себя только те IP которые есть в его списке. Так что список надо у них.

**Comment by sergeevabc** [comment]
Иван, действительно, с оптимизацией айпишников PAC похудел с 908 до 503 КБ, т.е. на 44%.
Правда, так и не работает — соединения висят на уровне ```Connecting…```, но мы на верном пути.

Хочется до конца автоматизировать интеграцию, для чего нужен CScript, который примет ```d_ipaddr = "\ ... ".match(/.{8}/g);```, а отдаст CSV для последующей обработки вашим ```make-ip-filter.csript.js```, т.е. в формате айпи+запятая+разрывстроки. Я попробовал создать ```restore-ips.cscript.js``` со следующим кодом, но получил ошибку ```(3, 34) Microsoft JScript compilation error: Syntax error```.
```javascript
function original_ips(antizapret_ips)
{
    csv = antizapret_ips.map(ip => {
        ip = parseInt(ip, 16)
        return [(ip >> 8*3) & 255, (ip >> 8*2) & 255, (ip >> 8) & 255, ip & 255].join(".")
    }).join(",\n");

    return csv;
}

if (typeof(WScript) != "undefined")
    WScript.Echo(original_ips(WScript.StdIn.ReadAll().split(",")));
```

**Comment by ivan386** [comment]
CScript понимает только древний JavaScript.

Так что надо писать [так](https://github.com/ivan386/js-ip-filter/blob/master/hex-list-to-ip-list.js):
```javascript
/* заменяем эту строку на d_ipaddr = "...".match(/.{8}/g); часть  */

function to_ip_list(hex_list)
{
	var ip_list = []
	for (var i = 0; i < hex_list.length; i++)
	{
		var ip = parseInt(hex_list[i], 16)
		ip_list.push([(ip >>> 8*3) & 255, (ip >>> 8*2) & 255, (ip >>> 8) & 255, ip & 255].join("."))
	}
	return ip_list
}

WScript.Echo(to_ip_list(d_ipaddr).join(",\n"))
```

**Comment by sergeevabc** [comment]
Подготовил скрипт [antizapret386.cmd][1], генерирующий [antizapret386.pac][2].
Вроде всё сходится, но чернокнижные сайты не открываются у меня. А у вас, Иван?

[1]: https://gist.github.com/sergeevabc/8a51ac9de9d40eb3160ee9944103a894
[2]: https://gist.githubusercontent.com/sergeevabc/6c5981b478233bbe3b98970e6bf629e0/raw/e7048a30505bbe3cd43dc60c4351396498b4a19e/antizapret386.pac

**Comment by ivan386** [comment]
Поправил функцию [to_ip_list](https://github.com/ivan386/js-ip-filter/blob/master/hex-list-to-ip-list.js). Забыл что JavaScript по умолчанию делает арифметический сдвиг.

**Comment by sergeevabc** [comment]
Всё равно PAC не работает. Попробуйте подключить antizapret386.pac (ссылка выше) у себя.

**Comment by ivan386** [comment]
Памяти не хватало. Пришлось вернуться к списку IP. Теперь должно работать но медленнее.

**Comment by sergeevabc** [comment]
Заработало — чернокнижные сайты открываются. Спасибо!

**Comment by sergeevabc** [comment]
Заработало — чернокнижные сайты открываются. Спасибо!
cc: @valdikss

**Comment by ivan386** [comment]
Я попробовал по другому сделать. По памяти теперь влезает и работает быстро.

**Comment by sergeevabc** [comment]
Подтверждаю, на Win7+FF63 работает.

**Comment by sergeevabc** [comment]
Иван, а вы знакомы с другими [предложениями][1] по оптимизации? Может быть, там что-то почерпнуть. И далее: на Хабре вы также предлагали оптимизировать доменную часть (в частности, что-то связанное с IndexOf). Если пойдём в эту степь, то я открою новый запрос. 

[1]: https://github.com/anticensority/runet-censorship-bypass/issues/13

**Comment by ivan386** [comment]
Сжатие доменов будет в новом репозитарии. Предложения я почитал но не всё.

**Comment by ivan386** [comment]
Сжатие доменов здесь: https://github.com/ivan386/js-domain-filter

После полного сжатия антизапрета proxy.pac занимает 370KB

**Comment by ValdikSS** [comment]
Сделал в листе base85, но разницу не делал. С base85 и разницей будет ещё меньше размер файла.

**Comment by ivan386** [comment]
@ValdikSS 
 Я уже использую знаки + и - для битовых полей и повторов. Надо будет либо алфавит менять либо другие символы для них использовать. Также включил в список и диапазоны которые сжимаются до серии "1/a 1/a 1/a"(это три диапазона) похоже что какую-то пару можно объединить в один диапазон. IP уже сжимать не так итересно. Они уже пока не больше 100KB занимают у меня.

Бинарный поиск то по быстрее искать будет IP и домены(аналог indexOf):
```js
function search(list, value)
{
	var start = 0
	var size = list.length
	var pos = list.length / 2 | 0
	for(;size>0;)
	{
		var list_value = list[start + pos]
		if (list_value == value)
			return start + pos;
		else if (list_value > value)
		{
			size = pos;
			pos = (size / 2) | 0
		}
		else
		{
			size = size - pos - 1
			start = start + pos + 1
			pos = (size / 2) | 0
		}
	}
	return -1;
}
```
Только перед поиском нужно выполнить sort() списка.

@sergeevabc в связи со сменой HEX на Base85 нужно поменять функцию to_ip_list на это [base85-list-to-ip-list.js](https://github.com/ivan386/js-ip-filter/blob/master/base85-list-to-ip-list.js)

**Comment by sergeevabc** [comment]
@ivan386, обновил [antizapret386.cmd][1], сменив HEX на BASE85.
После запуска сегодняшние 822311 байт худеют до 462564 (на 44%).
Правда, сам скрипт работает аж 20 секунд.

[1]: https://gist.github.com/sergeevabc/8a51ac9de9d40eb3160ee9944103a894

**Comment by sergeevabc** [comment]
@ivan386, я выяснил, что замедление работы скрипта с 5 до 20 секунд, чего раньше не было, происходит на шаге получения дельты из обычных айпишников (make-ip-filter.cscript.js).

**Comment by ivan386** [comment]
@sergeevabc Ускорил немного.

**Comment by sergeevabc** [comment]
@ivan386, вижу ускорение на 1-1,5 секунды, но это капля в море (скрипт работает 18,5–19 секунд).
Думается, связано с какими-то экспериментами последней недели, а не переходом на Base85.

**Comment by ivan386** [comment]
@sergeevabc У меня то всё за 3 секунды выполняется. Я добавил в скрипт замер времени. Надо понять что тормозит. Скрипт выведет время выполнения каждой части в консоль.

**Comment by sergeevabc** [comment]
@ivan386, вижу следующее:
```
Parsing     1500
Delta sort  809
Delta calc  283
Bitset      12103
Reduce      38
Print       37
```

Если взять дельту от прежнего запуска (ips_delta.tmp), минуя создание новой дельты, т.е.
```
rem 2.3 Получаем дельту из обычных айпишников
rem cscript /nologo ips_csv2delta.tmp.js < ips_csv.tmp > ips_delta.tmp
```
тогда скрипт antizapret386.cmd работает как раз 3 секунды.

**Comment by ivan386** [comment]
Отменил bitset. Надо понять что с ним не так.

**Comment by ivan386** [comment]
@sergeevabc Доработал bitset. Как теперь результаты?

**Comment by sergeevabc** [comment]
@ivan386, сейчас у @ValdikSS странность с Антизапретом — тот весит 411 Кб (вместо недавних ~800), из которых на айпи (в виде CSV) приходится всего 22 Кб. Поэтому antizapret386.cmd закономерно работает почти мигом:
```
Read       0         
Parsing    20        
Delta sort 10        
Delta calc 10        
Bitset     0         
Reduce     0         
Print      0         
```

**Comment by ValdikSS** [comment]
Изменил сортировку на `sort -un`, а оказалось, так нельзя:

```
GNU Sort: ‘-u’: sort -u and sort | uniq are equivalent, but this equivalence does not extend to arbitrary sort options. For example, sort -n -u inspects only the value of the initial numeric string…

$ cat addr.txt
19.20.203.5
19.20.21.22

$ sort -un addr.txt
19.20.203.5

:/
```

**Comment by sergeevabc** [comment]
@ivan386, после починки Антизапрета получил следующие метрики:
```
Read       120         
Parsing    1157        
Delta sort 880         
Delta calc 264         
Bitset     119         
Reduce     36          
Print      34          
```
Скрипт отработал за 5,5 секунд (победа!), Антизапрет похудел с 829 Кб до 457 Кб (на 44,87%).

**Comment by sergeevabc** [comment]
Последние дни @ValdikSS несколько раз переделывал сжатие айпишников Антизапрета, а смотришь на результат и грустно: оригинал 667 Кб против [здешних][1] 490 Кб. Спрашивается, почему не взяли более эффективный (и уже проверенный) алгоритм Ивана386?

[1]: https://gist.githubusercontent.com/sergeevabc/6c5981b478233bbe3b98970e6bf629e0/raw/18fa6aab7fcbb4ec51147603ba40c1ebe5271306/antizapret386.pac

**Comment by ValdikSS** [comment]
У меня уже были наработки по разности, а скрипты из этого репозитория я не знаю, как запускать.

**Comment by sergeevabc** [comment]
@ValdikSS Гм, вынуждаете догадываться, в чём именно сложность. Есть [antizapret386.cmd][1], где по шагам расписано, что на что меняется: айпишники оптимизируются и заменяют старые, а чуть ниже добавляется немного кода. Да, этот батник предназначен для Windows, но за исключением CScript использует юниксовые утилиты (wget, awk, sed, rm). Выходит, у вас сложность с тем, чтобы чем-то заменить CScript и натравить make-ip-filter.js на несжатые айпишники? Уверен, способ есть! Можем открыть новую тему и наверняка Иван что-то подскажет, а пока на ум приходят варианты:
```wine cscript file.js```
```node file.js```
```sudo apt-get install libmozjs-24-bin; sudo ln -sf /usr/bin/js24 file.js```

[1]: https://gist.github.com/sergeevabc/8a51ac9de9d40eb3160ee9944103a894

**Comment by ivan386** [comment]
@ValdikSS Если машина под Windows то пример здесь: [compile_proxy_pac.cmd](https://github.com/ivan386/js-ip-filter/blob/master/compile_proxy_pac.cmd)
```cmd
md temp
cscript /nologo make-ip-filter.cscript.js < temp\ip-list.csv > temp\proxy.pac
copy /b temp\proxy.pac+ip-filter.js+proxy_pac.tmp temp\proxy.pac
pause
```
На вход получает temp\ip-list.csv
Результат получим в temp\proxy.pac
В proxy_pac.tmp пример функции FindProxyForURL который нужно переделать под себя.

Я постарался написать  [make-ip-filter.cscript.js](https://github.com/ivan386/js-ip-filter/blob/master/make-ip-filter.cscript.js) универсально чтобы он мог выполниться и в браузере. Возможно он будет нормально работать и в node.js.

Функция make_ip_filter(ip_list) генерирует сам фильтр (строку). 

В сжатии я двинулся дальше посмотрев на результат:
1. Диапазоны. Я их просто копирую со входа и удаляю вложенные них IP и диапазоны.  
 Пример: 9/8 (9 разница с предыдущим значением; 8 бит под адрес узла; следующее значение считается от конца диапазона)
2. Места с повторяющейся разницей заменяются ей и количеством повторов.
 Пример: 9-3 (9 разница с предыдущим значением; -3 повторить 4 раза; 0 значит повторить один раз)
 Без сжатия: 9 9 9 9 9
3. Там где разницы маленькие но не одинаковые они сжимаются в 32 битное число. Позиция единичного бита означает разницу от предыдущего значения.
 Пример: +8vybcr (100000000010000000110011111011b)
 Без сжатия: 1 1 2 1 1 1 1 3 1 8 a

**Comment by sergeevabc** [comment]
Кстати, вспомнил статью на Хабре «[10 примеров того, как не нужно писать PAC-файлы][1]», где тоже оптимизируют код и замеряют скорость — авось пригодится.

[1]: https://habr.com/ru/company/icl_services/blog/328316/
