### ISSUE TITLE
[FIXED] Интеграция в Антизапрет, часть 2

### ISSUE THREAD

**Issue by sergeevabc** [ivan386/js-ip-filter#2]
Иван, доброго вечера.

Кажется, Валдик не собирается брать ваш алгоритм сжатия айпишников. Возможно, это связано с его желанием остаться на [awk-скриптах][1]. Ну, хозяин — барин. Однако его дельта-алгоритм не столь эффективен, как ваш, поэтому нужно обновить [скрипт][2] внедрения вашего алгоритма. Полагаю, обновление затронет два шага: преобразование айпишников Валдика в обычные (т.к. он сменил Base85 на свою дельту) и допиливание фильтра (т.к. он немного изменил [PAC][3]). Надеюсь на ваше участие и готов тестировать.

[1]: https://bitbucket.org/ValdikSS/antizapret/src
[2]: https://gist.github.com/sergeevabc/8a51ac9de9d40eb3160ee9944103a894
[3]: https://antizapret.prostovpn.org/proxy.pac

**Comment by ivan386** [comment]
Добавил декодер дельты.

**Comment by sergeevabc** [comment]
Качаю свежий Антизапрет, извлекаю дельту Валдика (пример), беру декодер дельты Валдика, добавляю в конец ```WScript.Echo(to_ip_list(WScript.StdIn.ReadAll()).join(",\n"))``` и запускаю через CScript. На выходе получаю странный файл весом в 4 Мб, который вверху столбика действительно заполнен айпишниками, а ближе к низу повторяющиеся ```0.0.0.0``` ([вот так][2]). Как быть, Иван?

[1]: https://termbin.com/y0a7
[2]: https://linx.li/ti8fi8kx.tmp

**Comment by ivan386** [comment]
@sergeevabc 
Надо:
1. взять полностью ```d_ipaddr="...".split(" ");``` 
2. добавить содержимое [delta-list-to-ip-list.js](https://github.com/ivan386/js-ip-filter/blob/master/delta-list-to-ip-list.js)
3. дописать ```WScript.Echo(to_ip_list(d_ipaddr).join(",\n"))```
4. запустить полученный скрипт.

Пример использования в [compile_from_antizapret_proxy_pac.cmd](https://github.com/ivan386/js-ip-filter/blob/master/compile_from_antizapret_proxy_pac.cmd)

```
copy /b temp\antizapret-proxy.pac+delta-list-to-ip-list.js+ranges-to-ip-list.js temp\proxy-pac-to-ip-csv.js
echo WScript.Echo(to_ip_list(d_ipaddr).join(",\n")) >> temp\proxy-pac-to-ip-csv.js
echo WScript.Echo(ranges_to_ip_list(special).join(",\n")) >> temp\proxy-pac-to-ip-csv.js
cscript /nologo temp\proxy-pac-to-ip-csv.js > temp\ip-list.csv
```

**Comment by sergeevabc** [comment]
Взял ```d_ipaddr``` [полностью][1], затем [дописал][2] ```Wscript```, затем запустил и вижу:
```
Microsoft JScript runtime error: 'd_ipaddr' is undefined
```

[1]: https://termbin.com/vw0c
[2]: https://termbin.com/4y4y

**Comment by ivan386** [comment]
@sergeevabc 
Либо поправить ситуацию так:
```
WScript.Echo(to_ip_list(WScript.StdIn.ReadAll().replace(/[\s\\]+/g," ").split(" ")).join(",\n"))
```

Это к вашему первому варианту.

**Comment by sergeevabc** [comment]
Вижу, после преобразования дельты Валдика в обычные, мы дописываем в тот же CSV и диапазоны:
```
...
222.186.153.76,
222.186.174.68,
223.26.28.181     <--- последний айпи, дальше идут диапазоны, запятой нет
103.246.200.0/22,
109.239.140.0/24,
...
```
А ничего, что нет запятой? Скрипт make-ip-filter.cscript.js отрабатывает без ошибок, но всё же.

**Comment by ivan386** [comment]
Запятые не обязательны. Их можно убрать.

**Comment by sergeevabc** [comment]
Айпишники и айпи-диапазоны Валдика распакованы в CSV, тот сжат по вашему методу, ниже добавлен айпи-фильтр, получилось [так][1]. Теперь допиливаю PAC Антизапрета. Вместо фрагмента ```var d_ipaddr ...   var special ... ];``` вставляю полученное на предыдущем шаге, выходит [так][2]. Осталось доработать логику: в прошлый раз мы меняли ```if (iphex) { ... }``` на ```if(oip && check_ip(oip)){yip = 1}```, но теперь этого нет. Как быть, Иван?

[1]: https://termbin.com/ltpye
[2]: https://qbin.io/whose-mutual-ltoq/raw

**Comment by sergeevabc** [comment]
Меня вот ещё смущает, что мы совместили айпишники и айпи-диапазоны, ведь у Валдика, судя по PAC, айпишники направляются на одну проксю, а диапазоны — на другую (```CCAHIHA...```).

**Comment by ivan386** [comment]
Теперь это строка:
```
if (iphex && d_ipaddr.indexOf(iphex) !== -1) {yip = 1;}
```
Которую аналогично надо заменить на:
```
if(oip && check_ip(oip)){yip = 1}
```

Диапазоны не надо включать в ip-filter так как для них другой прокси указан.
```
copy /b temp\antizapret-proxy.pac+delta-list-to-ip-list.js temp\proxy-pac-to-ip-csv.js
echo WScript.Echo(to_ip_list(d_ipaddr).join(",\n")) >> temp\proxy-pac-to-ip-csv.js
cscript /nologo temp\proxy-pac-to-ip-csv.js > temp\ip-list.csv
```
Соответственно special надо оставить как есть.

**Comment by sergeevabc** [comment]
Обновил [скрипт][1], который преобразует Антизапрет в следующий [вид][2], но в Лисе он не работает.

[1]: https://gist.github.com/sergeevabc/8a51ac9de9d40eb3160ee9944103a894
[2]: https://linx.li/s/antizapret386auto.pac

**Comment by sergeevabc** [comment]
Убрал Валдикову проверку ```if (d_ipaddr.length < 10) return "DIRECT"; // list is broken```, всё равно не работает.

**Comment by sergeevabc** [comment]
Ага, нужно выпиливать ещё больше, убирать весь следующий фрагмент, тогда наконец в Лисе работает.
```
  if (d_ipaddr.length < 10) return "DIRECT"; // list is broken

  if (!('indexOf' in Array.prototype)) {  ...  }

  if (!az_initialized) {  ...  }
```

Но IE 11, как не тянул зимой, так и тянет. Вероятно, ваш механизм сжатия слишком современный для него?

**Comment by ivan386** [comment]
Косяк был с фильтром:
```
var ip_filter="+-1 ...
```
Исправил.

**Comment by ivan386** [comment]
Эта часть как раз для IE. Её вырезать не надо.
```
  if (!('indexOf' in Array.prototype)) {
    Array.prototype.indexOf= function(find, i /*opt*/) {
      if (i===undefined) i= 0;
      if (i<0) i+= this.length;
      if (i<0) i= 0;
      for (var n= this.length; i<n; i++)
        if (i in this && this[i]===find)
          return i;
      return -1;
    };
  }
```

**Comment by ivan386** [comment]
А второй блок изменить так:
``` 
  if (!az_initialized) {
    for (var i = 0; i < special.length; i++) {
     special[i][1] = nmfc(special[i][1]);
    }
    az_initialized = 1;
  }
```

**Comment by sergeevabc** [comment]
> Косяк был с фильтром…

После исправления косяка размер скакнул с 546,625 до 633,861 байт, зато [теперь][1] работает даже в IE11.

Свежая статистика:
```
$ antizapret386.cmd

Read        236
Parsing     2672
Delta sort  1703
Delta calc  570
Bitset      304
Reduce      106
Print       129
  
Original:   837993 bytes
Compressed: 633861 bytes
Difference: 24.36%
``` 

[1]: https://gist.github.com/sergeevabc/6c5981b478233bbe3b98970e6bf629e0

**Comment by sergeevabc** [comment]
Иван, как думаете, почему после добавления правила для Тора, IE не принимает PAC?
```javascript
function FindProxyForURL(url, host) {

  if (host.endsWith(".onion")) {return "SOCKS5 127.0.0.1:9050";}

  if (!('indexOf' in Array.prototype)) { ...
```

**Comment by sergeevabc** [comment]
@valdikss, вам может быть интересно, что при внимательном и терпеливом содействии @ivan386 удалось ужать айпишники PAC Антизапрета ещё на 25%, сохранив работоспособность под основными браузерами.

**Comment by ValdikSS** [comment]
У меня есть отдельный скрипт, который сжимает индивидуальные адреса до диапазонов, где это возможно. Когда-нибудь я его интегрирую в PAC.
Зачем вы парсите PAC, а не создаете с нуля свой?

**Comment by sergeevabc** [comment]
@ValdikSS, пережимая адреса ресурсов из вашего скрипта, есть уверенность, что ваши прокси-сервера откроют поступающие сетевые обращения. А то мало ли, у кого-то лист окажется свежее или вы решите, что обращения на такой-то адрес неуместны и заблокируете его руками.
